name: fullstack-challenge
services:
    app:
        build:
            context: ./docker
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - redis
            - mysql
            - laravel-echo-server

    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:7
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    laravel-echo-server:
        build:
            context: ./docker
            dockerfile: Dockerfile.echo
        ports:
            - '6001:6001'
        volumes:
            - ./laravel-echo-server:/echo-server

    laravel-worker:
        build:
            context: ./docker
            dockerfile: Dockerfile.worker
        volumes:
            - .:/var/www/html
        depends_on:
            - redis
            - mysql

volumes:
    mysql_data:
    redis_data:
